# Notes

## Linear Model

In [125]:
# example of model y=ax+b. Find w = [a,b]^T and compute prediction x=5

import numpy as np

# setup model in standard format
X = np.array([[1,1], [1,3], [1,4]]) # adding a ones-column to account for offset
y = np.array([2,5,6])

# compute weights
w_star = np.linalg.inv(X.T @ X)@X.T@y

# compute y
input = [1,5]
y = input@w_star
y

7.499999999999998

## Association Mining

$support=\frac{X}{\lvert T \rvert}$

Support for an $item > 40\%$ means $0.4 \times \lvert T \rvert$ must be satisfied.

$confidence=\frac{support(X\bigcup Y)}{support(X)}$

### Apriori Algorithm
Given new candidate itemssets $c$ in C for $L_k$.
If $L_{k-1}$ does not contain a subset $s$ present in one of the $c$ itemsets. Then that $c$ is not considered.

## Naïve Bayes Classifier

$p\left(y \mid x_{1}, x_{2}, \ldots, x_{M}\right)=\frac{p\left(x_{1}, x_{2}, \ldots, x_{M} \mid y\right) p(y)}{\sum_{k=0}^{K-1} p\left(x_{1}, x_{2}, \ldots, x_{M} \mid y=k\right) p(y=k)}$

## AUC

$TPR / Recall / Sensitivity =\frac{\text { TP }}{\text { TP }+\text { FN }}$

$Specificity=\frac{\text { TN }}{\text { TN + FP }}$

FPR = $1 - Specificity=\frac{F P}{T N+F P}$

Total number of positive examples: $TP + FN$

Total number of negative examples: $FP + TN$

In [75]:
# compute AUC
from sklearn import metrics
y = np.array([0, 0, 0, 0, 1, 1, 1, 0, 0, 1])
pred = np.array([5.7, 6.0, 6.2, 6.3, 6.4, 6.6, 6.7, 6.9, 7.0, 7.4])
fpr, tpr, thresholds = metrics.roc_curve(y, pred, pos_label=1)
metrics.auc(fpr, tpr), thresholds

0.7500000000000001

## Gaussian Mixture Model

In [4]:
import numpy as np
from sklearn.mixture import GaussianMixture
X = np.array([[2.11, 1.15, 1.09]]).T
gm = GaussianMixture(n_components=3, random_state=0).fit(X)
gm.means_, gm._e_step(X), gm._m_step

#gm.predict([[0, 0], [12, 3]])

(array([[2.11],
        [1.09],
        [1.15]]),
 (4.890204457109357,
  array([[      0.        , -520200.        , -460800.        ],
         [-460800.        ,   -1800.        ,       0.        ],
         [-520199.99999999,       0.        ,   -1800.        ]])),
 <bound method GaussianMixture._m_step of GaussianMixture(n_components=3, random_state=0)>)

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import multivariate_normal

x = np.linspace(0, 5, 10, endpoint=False)
y = multivariate_normal.pdf(x, mean=2.5, cov=0.5)
fig1 = plt.figure()
ax = fig1.add_subplot(111)
ax.plot(x, y)


## Similarity

In [19]:
r = np.array([[1,1,1,1,0,1]])
s = np.array([[1,1,0,1,0,0]])

def jaccard(x,y):
  x = np.asarray(x, np.bool) # Not necessary, if you keep your data
  y = np.asarray(y, np.bool) # in a boolean array already!
  return np.double(np.bitwise_and(x, y).sum()) / x.size - np.double(np.bitwise_or(x, y).sum())

def smc(x,y):
  return np.double(np.bitwise_and(x,y).sum() + np.bitwise_not(x,y).sum()) / x.size


from sklearn.metrics.pairwise import cosine_similarity

print(f"SMC: {smc(r,s)}")
print(f"Jaccard: {jaccard(r,s)}")
print(f"CosineSimilarity: {cosine_similarity(r,s)}")

SMC: -1.3333333333333333
Jaccard: -5.166666666666667
CosineSimilarity: [[-0.97590007]]


/tmp/ipykernel_15602/642619845.py:6: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.asarray(x, np.bool) # Not necessary, if you keep your data
/tmp/ipykernel_15602/642619845.py:7: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = np.asarray(y, np.bool) # in a boolean array already!



## k-means

In [47]:
from sklearn.cluster import KMeans
x = np.array([[5.7, 6.0, 6.2, 6.3, 6.4, 6.6, 6.7, 6.9, 7.0, 7.4]]).T

kmeans = KMeans(n_clusters=2).fit(x)
#kmeans = KMeans(n_clusters=2, init=np.array([[x.mean]]).T).fit(x)

kmeans.cluster_centers_, kmeans.labels_

(array([[6.92],
        [6.12]]),
 array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0], dtype=int32))

## KNN

In [10]:
# find k-nearest neighbours
from sklearn.neighbors import NearestNeighbors
samples = np.array([[5.7, 6.0, 6.2, 6.3, 6.4, 6.6, 6.7, 6.9, 7.0, 7.4]]).T
neigh = NearestNeighbors(n_neighbors=3)
neigh.fit(samples)
neigh.kneighbors([[7.4]])

# compute densities and average relative densities (modify K and arrays)
K = 3
(d1, d2, d3) = (1/K * np.array([0.1,0.3,0.4])).sum()**-1, (1/K*np.array([0.1,0.2,0.3])).sum()**-1, (1/K*np.array([0.1,0.2,0.3])).sum()**-1
di = (1/K * np.array([0.4, 0.5, 0.7])).sum()**-1
ard = di/(1/K*np.array([d1,d2,d3])).sum()
ard

<bound method BaseEstimator.get_params of NearestNeighbors(n_neighbors=3)>

## PCA

In [ ]:
# variance explained
def variance_explained(S, S_sub):
    var_expl_pca = (S_sub**2).sum() / sum(S**2)
    print("$Var_{Expl} Range$: ", var_expl_pca)

S = np.array([14.14, 11.41, 9.46, 4.19, 0.17]) # s_i

# modify range
S_sub = S[:3]
print(f"Selected values: {S_sub}")
variance_explained(S, S_sub)

## Decision Trees

**Impurity Gain**
$\Delta=I(r)-\sum_{k=1}^{K} \frac{N\left(v_{k}\right)}{N(r)} I\left(v_{k}\right)$

And then the 3 measure methods. See the image in this directory..




In [29]:
# Example of Impurity gain using Gini
I_r = 1-pow(5/15, 2)-pow(10/15, 2) # N(r) = 15
I_1 = 1-pow(1/5, 2)-pow(4/5, 2) # N(v1) = 5
I_2 = 1-pow(4/10, 2)-pow(6/10, 2) # N(v2) = 10

Impurity_Gain = I_r-5/15*I_1-10/15*I_2
Impurity_Gain

0.017777777777777892

## Adaboost

error rate
$\epsilon_{t}=\sum_{i=1}^{N} w_{i}(t)\left(1-\delta_{f_{t}\left(\boldsymbol{x}_{i}\right), y_{i}}\right)$ where $\delta_{a, b}=\left\{\begin{array}{ll}1 & \text { if } a=b \\ 0 & \text { if } a \neq b\end{array}\right.$

importance of classifier
$\alpha_{t}=\frac{1}{2} \log \frac{1-\epsilon_{t}}{\epsilon_{t}}$

## Decision Boundaries (how to interpret)
- Linear boundaries: Multinomial Regression
- Smooth curvy boundaries: ANN
- Axis aligned boundaries: Classification Tree
- Complex non-smooth boundaries: 3-nearest neighbours

# Scratchbook